  
**2**<br> 

a.<br> 

s({e}) = $\frac{8}{10}$ = 0.8 <br>

s({b,d}) = $\frac{2}{10}$ = 0.2 <br>

s({b,d,e}) = 0.2 <br>

b.<br> 

c({b,d} -> {e}) = $\frac{s({b,d,e})}{s({b,d})}$ = $\frac{0.2}{0.2}$ = 1<br>

c({e} -> {b,d}) = $\frac{0.2}{0.8}$ = 0.25 <br>

confidence is clearly not a symmetric metric <br>

c. <br>

> s({e}) = $\frac{4}{5}$ = 0.8<br>

> s({b,d}) = $\frac{5}{5}$ = 1 <br>

> s({b,d,e}) = $\frac{4}{5}$ = 0.8 <br>

d.<br> 

> c({b,d} -> {e}) = 0.8 <br>

> c({e} -> {b,d}) = 1 <br> 

e.<br> 

> we cannot really say anything about confidence or support when we change market baskets. <br> 

**6**<br>

a.<br>  

> rules = $3^d - 2^{d+1} + 1$ = $3^6 - 2^{7} + 1$ = 602 <br>

b.<br>  

> 4 is the maximum frequent set possible<br>

c.<br>  

> this is n choose k. So in this case 6 choose 3 so = 20 <br>

d.<br>  

> {bread, butter} <br>

e.<br>  

> {beer, cookies} <br>

**10** <br>

a) L1, L3, L5, L9, and L11 <br>

b) {1,4,5}{1,5,8}, {4,5,8} <br>

**12** <br>

M = {{a, b},{b, c},{c, d},{a, d, e}, {b, d, e}} <br>

C = {{a},{b},{c},{d},{a,b},{b,c},{b,d},{c,d},{d,e},{a,d,e},{b,d,e}}<br>

N = {{e}, {a,d},{a,e},{b,e}} <br>

I = {{a,c},{a,b,c},{a,b,d},{a,b,e},{a,c,d},{a,c,e},{b,c,d},{b,c,e},{c,d,e},{a,b,c,d},{a,b,c,e},{a,b,d,e},
{a,c,d,e},{b,c,d,e},{a,b,c,d,e}}<br>

**13** <br>

a.<br>

|          | $c$ | $\hat{c}$|   
|----------|---|--------|---|
| $b$      | 3 |   4    | 7 |
| $\hat{b}$| 2 |   1    | 3 |
|          | 5 |   5    | 10|

|          | $d$ | $\hat{d}$|   
|----------|---|--------|---|
| $a$      | 4 |   1    | 5 |
| $\hat{a}$| 5 |   0    | 5 |
|          | 9 |   1    | 10|

|          | $d$ | $\hat{d}$|   
|----------|---|--------|---|
| $b$      | 6 |   1    | 7 |
| $\hat{b}$| 3 |   0    | 3 |
|          | 9 |   1    | 10|

|          | $c$ | $\hat{c}$|   
|----------|---|--------|---|
| $e$      | 2 |   4    | 6 |
| $\hat{e}$| 3 |   1    | 4 |
|          | 5 |   5    | 10|

|          | $a$ | $\hat{a}$|   
|----------|---|--------|---|
| $c$      | 2 |   3    | 5 |
| $\hat{c}$| 3 |   2    | 5 |
|          | 5 |   5    | 10|

b.<br>

support: <br>

1. {b} -> {d} : 0.6

2. {a} -> {d} : 0.4

3. {b} -> {c} : 0.3

4. {c} -> {a} tied {e} -> {c} : 0.2

confidence:<br>

1. {b} -> {d} : 0.86

2. {a} -> {d} : 0.8

3. {b} -> {c} : 0.43

4. {c} -> {a} : 0.4

5. {e} -> {c} : 0.33

interest:<br>

1. {b} -> {d} : 0.77

2. {a} -> {d} : 0.72

3. {b} -> {c} : 0.21

4. {c} -> {a} : 0.2

5. {e} -> {c} : 0.17

IS:<br>

1. {b} -> {d} : 0.756

2. {a} -> {d} : 0.696

3. {b} -> {c} : 0.507

4. {c} -> {a} : 0.4

5. {e} -> {c} : 0.37

Klosgen:<br>

1. {b} -> {d} : -0.03

2. {b} -> {c} tied {c} -> {a}: -0.04

3. {a} -> {d} : -0.06

4. {e} -> {c} : -0.08

Odds Ratio:<br>

1. {c} -> {a} : 0.44

2. {b} -> {c} : 0.375

3. {e} -> {c} : 0.16

4. {b} -> {d} : 0

5. {a} -> {d} : 0


**20** <br>

a. <br>

- S(A,B) = 0.09 

- Interest = 9

- Correlation = 0.89

- Confidence A -> B: 0.9

- Confidence B -> A: 0.9

b.<br>

- S(A,B)= 0.89

- Interest = 1.099

- Correlation = 0.89

- Confidence A -> B: 0.99

- Confidence B -> A: 0.99

c. <br>
Support, Interest, and Confidence cannot have their f11 and f00 inverted. While correlation is affected by an inversion.

In [3]:
import numpy as np
import pandas as pd

from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

%matplotlib inline

## Problem 1

Load the *Online  Retaildataset* (**Online Retail.xlsx**) from the **UCI Machine Learning Repository** into Python using a Pandas dataframe.  Using the apriori module from the **MLxtend** library,  generate Frequent Itemsets for all trans-actions for the country of France.  What itemset has the largest support?  Set the minimum support threshold to 5% and extract frequent itemsets, and use them as input to the association rules module.  Use each of the confidence and lift metrics to extract the association rules with the highest values, respectively. What are the antecedents and consequents of each rule?  Is the rule with the highest confidence the same as the rule with the highest lift?  Why or why not?

### Answer :-
The itemset with the largest support is {'RABBIT NIGHT LIGHT'}. 

The rule with the highest confidence is {'SET/20 RED RETROSPOT PAPER NAPKINS','SET/6 RED SPOTTY PAPER PLATES'} -> {'SET/6 RED SPOTTY PAPER CUPS'}. 

The rule with the highest lift is {'PACK OF 6 SKULL PAPER CUPS'} -> {'PACK OF 6 SKULL PAPER PLATES'}. 

The rule with the highest confidence and the rule with the highest lift are different. This because the lift takes into account the joint support of the rule and both the support of the antecedents and consequents support. Confidence only takes into account joint support of the rule and the antecedent's support.

In [92]:
df = pd.read_excel('http://archive.ics.uci.edu/ml/machine-learning-databases/00352/Online%20Retail.xlsx')
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [93]:
df.describe()

            Quantity      UnitPrice     CustomerID
count  541909.000000  541909.000000  406829.000000
mean        9.552250       4.611114   15287.690570
std       218.081158      96.759853    1713.600303
min    -80995.000000  -11062.060000   12346.000000
25%         1.000000       1.250000   13953.000000
50%         3.000000       2.080000   15152.000000
75%        10.000000       4.130000   16791.000000
max     80995.000000   38970.000000   18287.000000

In [94]:
df['Description'] = df['Description'].str.strip()
df.dropna(axis = 0, subset=['InvoiceNo'], inplace = True)
df['InvoiceNo'] = df['InvoiceNo'].astype('str')
df = df[~df['InvoiceNo'].str.contains('C')]

In [95]:
df.describe()

            Quantity      UnitPrice     CustomerID
count  532621.000000  532621.000000  397924.000000
mean       10.239972       3.847621   15294.315171
std       159.593551      41.758023    1713.169877
min     -9600.000000  -11062.060000   12346.000000
25%         1.000000       1.250000   13969.000000
50%         3.000000       2.080000   15159.000000
75%        10.000000       4.130000   16795.000000
max     80995.000000   13541.330000   18287.000000

In [96]:
france_df = df[df["Country"] == "France"]
france_df.describe()

          Quantity    UnitPrice    CustomerID
count  8408.000000  8408.000000   8342.000000
mean     13.333016     4.399713  12678.377128
std      21.069963    65.505260    277.279060
min       1.000000     0.000000  12413.000000
25%       6.000000     1.250000  12571.000000
50%      10.000000     1.790000  12678.000000
75%      12.000000     3.750000  12689.000000
max     912.000000  4161.060000  14277.000000

In [97]:
french_basket = (france_df
          .groupby(['InvoiceNo', 'Description'])['Quantity']
          .sum().unstack().reset_index().fillna(0)
          .set_index('InvoiceNo'))

french_basket.tail()

Description,10 COLOUR SPACEBOY PEN,12 COLOURED PARTY BALLOONS,12 EGG HOUSE PAINTED WOOD,12 MESSAGE CARDS WITH ENVELOPES,12 PENCIL SMALL TUBE WOODLAND,12 PENCILS SMALL TUBE RED RETROSPOT,12 PENCILS SMALL TUBE SKULL,12 PENCILS TALL TUBE POSY,12 PENCILS TALL TUBE RED RETROSPOT,12 PENCILS TALL TUBE WOODLAND,...,WRAP VINTAGE PETALS DESIGN,YELLOW COAT RACK PARIS FASHION,YELLOW GIANT GARDEN THERMOMETER,YELLOW SHARK HELICOPTER,ZINC STAR T-LIGHT HOLDER,ZINC FOLKART SLEIGH BELLS,ZINC HERB GARDEN CONTAINER,ZINC METAL HEART DECORATION,ZINC T-LIGHT HOLDER STAR LARGE,ZINC T-LIGHT HOLDER STARS SMALL
InvoiceNo,,,,,,,,,,,,,,,,,,,,,
580986,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
581001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
581171,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
581279,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
581587,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [99]:
def sum_to_boolean(x):
    if x<=0:
        return 0
    else:
        return 1

french_basket_sg = french_basket.applymap(sum_to_boolean)

In [100]:
french_basket_sg.drop('POSTAGE', inplace=True, axis=1)
french_basket_sg.describe()

Description,10 COLOUR SPACEBOY PEN,12 COLOURED PARTY BALLOONS,12 EGG HOUSE PAINTED WOOD,12 MESSAGE CARDS WITH ENVELOPES,12 PENCIL SMALL TUBE WOODLAND,12 PENCILS SMALL TUBE RED RETROSPOT,12 PENCILS SMALL TUBE SKULL,12 PENCILS TALL TUBE POSY,12 PENCILS TALL TUBE RED RETROSPOT,12 PENCILS TALL TUBE WOODLAND,...,WRAP VINTAGE PETALS DESIGN,YELLOW COAT RACK PARIS FASHION,YELLOW GIANT GARDEN THERMOMETER,YELLOW SHARK HELICOPTER,ZINC STAR T-LIGHT HOLDER,ZINC FOLKART SLEIGH BELLS,ZINC HERB GARDEN CONTAINER,ZINC METAL HEART DECORATION,ZINC T-LIGHT HOLDER STAR LARGE,ZINC T-LIGHT HOLDER STARS SMALL
count,392.000000,392.000000,392.000000,392.000000,392.000000,392.000000,392.000000,392.000000,392.000000,392.000000,...,392.000000,392.000000,392.000000,392.000000,392.000000,392.000000,392.000000,392.000000,392.000000,392.000000
mean,0.030612,0.015306,0.002551,0.005102,0.015306,0.017857,0.017857,0.002551,0.022959,0.015306,...,0.007653,0.005102,0.002551,0.002551,0.002551,0.017857,0.002551,0.010204,0.002551,0.005102
std,0.172485,0.122924,0.050508,0.071337,0.122924,0.132601,0.132601,0.050508,0.149965,0.122924,...,0.087258,0.071337,0.050508,0.050508,0.050508,0.132601,0.050508,0.100627,0.050508,0.071337
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [101]:
frequent_itemsets = apriori(french_basket_sg, min_support = 0.05, use_colnames = True)

frequent_itemsets.sort_values('support', ascending = False).head()

     support                              itemsets
46  0.188776                  (RABBIT NIGHT LIGHT)
52  0.181122       (RED TOADSTOOL LED NIGHT LIGHT)
44  0.170918    (PLASTERS IN TIN WOODLAND ANIMALS)
40  0.168367       (PLASTERS IN TIN CIRCUS PARADE)
59  0.158163  (ROUND SNACK BOXES SET OF4 WOODLAND)

In [102]:
frequent_itemsets.sort_values('support', ascending = False).tail()

    support                                           itemsets
6   0.05102                            (BLUE HARMONICA IN BOX)
32  0.05102                   (MINI LIGHTS WOODLAND MUSHROOMS)
34  0.05102                    (PACK OF 20 NAPKINS RED APPLES)
70  0.05102                          (SPACEBOY CHILDRENS BOWL)
79  0.05102  (ALARM CLOCK BAKELIKE RED, ROUND SNACK BOXES S...

In [112]:
con_rules = association_rules(frequent_itemsets, metric = "confidence", min_threshold = 0.7)
con_rules.sort_values('confidence',ascending = False)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
25,"(SET/6 RED SPOTTY PAPER PLATES, SET/20 RED RET...",(SET/6 RED SPOTTY PAPER CUPS),0.102041,0.137755,0.099490,0.975000,7.077778,0.085433,34.489796
24,"(SET/6 RED SPOTTY PAPER CUPS, SET/20 RED RETRO...",(SET/6 RED SPOTTY PAPER PLATES),0.102041,0.127551,0.099490,0.975000,7.644000,0.086474,34.897959
18,(SET/6 RED SPOTTY PAPER PLATES),(SET/6 RED SPOTTY PAPER CUPS),0.127551,0.137755,0.122449,0.960000,6.968889,0.104878,21.556122
7,(CHILDRENS CUTLERY SPACEBOY),(CHILDRENS CUTLERY DOLLY GIRL),0.068878,0.071429,0.063776,0.925926,12.962963,0.058856,12.535714
10,(PACK OF 6 SKULL PAPER PLATES),(PACK OF 6 SKULL PAPER CUPS),0.056122,0.063776,0.051020,0.909091,14.254545,0.047441,10.298469
6,(CHILDRENS CUTLERY DOLLY GIRL),(CHILDRENS CUTLERY SPACEBOY),0.071429,0.068878,0.063776,0.892857,12.962963,0.058856,8.690476
17,(SET/6 RED SPOTTY PAPER CUPS),(SET/6 RED SPOTTY PAPER PLATES),0.137755,0.127551,0.122449,0.888889,6.968889,0.104878,7.852041
21,"(ALARM CLOCK BAKELIKE RED, ALARM CLOCK BAKELIK...",(ALARM CLOCK BAKELIKE GREEN),0.073980,0.096939,0.063776,0.862069,8.892922,0.056604,6.547194
20,"(ALARM CLOCK BAKELIKE GREEN, ALARM CLOCK BAKEL...",(ALARM CLOCK BAKELIKE RED),0.073980,0.094388,0.063776,0.862069,9.133271,0.056793,6.565689
3,(ALARM CLOCK BAKELIKE RED),(ALARM CLOCK BAKELIKE GREEN),0.094388,0.096939,0.079082,0.837838,8.642959,0.069932,5.568878
2,(ALARM CLOCK BAKELIKE GREEN),(ALARM CLOCK BAKELIKE RED),0.096939,0.094388,0.079082,0.815789,8.642959,0.069932,4.916181
23,"(SET/6 RED SPOTTY PAPER CUPS, SET/6 RED SPOTTY...",(SET/20 RED RETROSPOT PAPER NAPKINS),0.122449,0.132653,0.099490,0.812500,6.125000,0.083247,4.625850
19,"(ALARM CLOCK BAKELIKE GREEN, ALARM CLOCK BAKEL...",(ALARM CLOCK BAKELIKE PINK),0.079082,0.102041,0.063776,0.806452,7.903226,0.055706,4.639456
9,(PACK OF 6 SKULL PAPER CUPS),(PACK OF 6 SKULL PAPER PLATES),0.063776,0.056122,0.051020,0.800000,14.254545,0.047441,4.719388
15,(SET/6 RED SPOTTY PAPER PLATES),(SET/20 RED RETROSPOT PAPER NAPKINS),0.127551,0.132653,0.102041,0.800000,6.030769,0.085121,4.336735
4,(ALARM CLOCK BAKELIKE RED),(ALARM CLOCK BAKELIKE PINK),0.094388,0.102041,0.073980,0.783784,7.681081,0.064348,4.153061
27,(SET/6 RED SPOTTY PAPER PLATES),"(SET/6 RED SPOTTY PAPER CUPS, SET/20 RED RETRO...",0.127551,0.102041,0.099490,0.780000,7.644000,0.086474,4.081633
22,"(PLASTERS IN TIN SPACEBOY, PLASTERS IN TIN CIR...",(PLASTERS IN TIN WOODLAND ANIMALS),0.089286,0.170918,0.068878,0.771429,4.513433,0.053617,3.627232
16,(SET/20 RED RETROSPOT PAPER NAPKINS),(SET/6 RED SPOTTY PAPER PLATES),0.132653,0.127551,0.102041,0.769231,6.030769,0.085121,3.780612
14,(SET/20 RED RETROSPOT PAPER NAPKINS),(SET/6 RED SPOTTY PAPER CUPS),0.132653,0.137755,0.102041,0.769231,5.584046,0.083767,3.736395
0,(ALARM CLOCK BAKELIKE GREEN),(ALARM CLOCK BAKELIKE PINK),0.096939,0.102041,0.073980,0.763158,7.478947,0.064088,3.791383
12,(PLASTERS IN TIN SPACEBOY),(PLASTERS IN TIN WOODLAND ANIMALS),0.137755,0.170918,0.104592,0.759259,4.442233,0.081047,3.443878
28,(SET/20 RED RETROSPOT PAPER NAPKINS),"(SET/6 RED SPOTTY PAPER CUPS, SET/6 RED SPOTTY...",0.132653,0.122449,0.099490,0.750000,6.125000,0.083247,3.510204
13,(SET/6 RED SPOTTY PAPER CUPS),(SET/20 RED RETROSPOT PAPER NAPKINS),0.137755,0.132653,0.102041,0.740741,5.584046,0.083767,3.345481
1,(ALARM CLOCK BAKELIKE PINK),(ALARM CLOCK BAKELIKE GREEN),0.102041,0.096939,0.073980,0.725000,7.478947,0.064088,3.283859
5,(ALARM CLOCK BAKELIKE PINK),(ALARM CLOCK BAKELIKE RED),0.102041,0.094388,0.073980,0.725000,7.681081,0.064348,3.293135
26,(SET/6 RED SPOTTY PAPER CUPS),"(SET/6 RED SPOTTY PAPER PLATES, SET/20 RED RET...",0.137755,0.102041,0.099490,0.722222,7.077778,0.085433,3.232653
11,(PLASTERS IN TIN STRONGMAN),(PLASTERS IN TIN CIRCUS PARADE),0.081633,0.168367,0.058673,0.718750,4.268939,0.044929,2.956916
8,(DOLLY GIRL LUNCH BOX),(SPACEBOY LUNCH BOX),0.099490,0.125000,0.071429,0.717949,5.743590,0.058992,3.102273

In [111]:
lift_rules = association_rules(frequent_itemsets, metric = "lift", min_threshold = 1)
lift_rules.sort_values('lift',ascending = False).head()

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
38,(PACK OF 6 SKULL PAPER CUPS),(PACK OF 6 SKULL PAPER PLATES),0.063776,0.056122,0.051020,0.800000,14.254545,0.047441,4.719388
39,(PACK OF 6 SKULL PAPER PLATES),(PACK OF 6 SKULL PAPER CUPS),0.056122,0.063776,0.051020,0.909091,14.254545,0.047441,10.298469
8,(CHILDRENS CUTLERY DOLLY GIRL),(CHILDRENS CUTLERY SPACEBOY),0.071429,0.068878,0.063776,0.892857,12.962963,0.058856,8.690476
9,(CHILDRENS CUTLERY SPACEBOY),(CHILDRENS CUTLERY DOLLY GIRL),0.068878,0.071429,0.063776,0.925926,12.962963,0.058856,12.535714
69,"(ALARM CLOCK BAKELIKE GREEN, ALARM CLOCK BAKEL...",(ALARM CLOCK BAKELIKE RED),0.073980,0.094388,0.063776,0.862069,9.133271,0.056793,6.565689

## Problem 2

Load the *Extended Bakery* dataset (**75000-out2-binary.csv**) into Python using a Pandas dataframe.  Calculate the binary correlation coefficient Φ for the *Chocolate  Coffee* and *Chocolate  Cake* items.   Are  these  two  items  symmetric binary variables?  Provide supporting calculations.  Would the association rules {**Chocolate Coffee**} ⇒ {**Chocolate Cake**} have  the  same  value  for  Φ  as {**Chocolate Cake**} ⇒ {**Chocolate Coffee**}?

### Answer :-

The binary correlation is 0.4856. These items are assymmetric binary variables. <br>

s({Chocolate Cake}) = 0.0835 <br>
s({Chocolate Coffee}) = 0.08314 <br>
s({Chocolate Cake},{Chocolate Coffee}) = 0.4404 <br>

The correlation coefficient is the same for both rules <br>{Chocolate Coffee} -> {Chocolate Cake} and {Chocolate Cake} -> {Chocolate Coffee} because the correlation coefficient is invariant.

In [4]:
intial_bakery_df = pd.read_csv("75000-out2-binary.csv")
intial_bakery_df.describe()

,Transaction Number,Chocolate Cake,Lemon Cake,Casino Cake,Opera Cake,Strawberry Cake,Truffle Cake,Chocolate Eclair,Coffee Eclair,Vanilla Eclair,...,Lemon Lemonade,Raspberry Lemonade,Orange Juice,Green Tea,Bottled Water,Hot Coffee,Chocolate Coffee,Vanilla Frappuccino,Cherry Soda,Single Espresso
count,75000.000000,75000.000000,75000.000000,75000.000000,75000.000000,75000.000000,75000.000000,75000.000000,75000.000000,75000.000000,...,75000.000000,75000.000000,75000.000000,75000.000000,75000.000000,75000.000000,75000.000000,75000.000000,75000.000000,75000.000000
mean,37500.500000,0.083533,0.083613,0.075013,0.082093,0.092640,0.082240,0.042373,0.109240,0.042520,...,0.068240,0.067747,0.091613,0.062467,0.075200,0.102667,0.083147,0.077467,0.061987,0.067973
std,21650.779432,0.276689,0.276809,0.263415,0.274509,0.289929,0.274732,0.201441,0.311942,0.201774,...,0.252159,0.251312,0.288481,0.242003,0.263716,0.303525,0.276106,0.267332,0.241133,0.251702
min,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,18750.750000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,37500.500000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,56250.250000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,75000.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [90]:
intial_bakery_df[(intial_bakery_df["Chocolate Cake"] == 1) & (intial_bakery_df["Chocolate Coffee"] == 0)]["Transaction Number"].count()

2962

In [8]:
bake_f = apriori(intial_bakery_df.drop(columns="Transaction Number"), min_support = 0.04, use_colnames = True)
bake_f.sort_values('support', ascending = False)

     support                                   itemsets
7   0.109240                            (Coffee Eclair)
45  0.102667                               (Hot Coffee)
28  0.100747                             (Tuile Cookie)
18  0.093160                              (Cherry Tart)
4   0.092640                          (Strawberry Cake)
35  0.092573                           (Apricot Danish)
42  0.091613                             (Orange Juice)
22  0.090440                         (Gongolais Cookie)
27  0.089773                          (Marzipan Cookie)
14  0.084827                               (Berry Tart)
32  0.083987                        (Apricot Croissant)
1   0.083613                               (Lemon Cake)
0   0.083533                           (Chocolate Cake)
46  0.083147                         (Chocolate Coffee)
16  0.082947                           (Blueberry Tart)
9   0.082747                            (Napoleon Cake)
5   0.082240                             (Truffle Cake)
33  0.082213                         (Cheese Croissant)
3   0.082093                               (Opera Cake)
47  0.077467                      (Vanilla Frappuccino)
37  0.077200                             (Almond Twist)
11  0.077120                                (Apple Pie)
15  0.075867                          (Blackberry Tart)
19  0.075800                               (Lemon Tart)
44  0.075200                            (Bottled Water)
2   0.075013                              (Casino Cake)
17  0.073720                           (Chocolate Tart)
40  0.068240                           (Lemon Lemonade)
12  0.068227                               (Apple Tart)
24  0.068013                             (Lemon Cookie)
49  0.067973                          (Single Espresso)
29  0.067853                            (Walnut Cookie)
41  0.067747                       (Raspberry Lemonade)
36  0.067693                             (Apple Danish)
23  0.067640                         (Raspberry Cookie)
31  0.067293                          (Apple Croissant)
43  0.062467                                (Green Tea)
48  0.061987                              (Cherry Soda)
56  0.053093              (Cherry Tart, Apricot Danish)
57  0.050920            (Tuile Cookie, Marzipan Cookie)
39  0.044093                         (Blueberry Danish)
50  0.044040         (Chocolate Cake, Chocolate Coffee)
54  0.043920           (Truffle Cake, Gongolais Cookie)
55  0.043507        (Blueberry Tart, Apricot Croissant)
51  0.043373                  (Opera Cake, Cherry Tart)
20  0.043373                               (Pecan Tart)
34  0.043240                      (Chocolate Croissant)
21  0.043240                           (Ganache Cookie)
53  0.043147           (Strawberry Cake, Napoleon Cake)
58  0.043067           (Cheese Croissant, Orange Juice)
52  0.043027               (Opera Cake, Apricot Danish)
30  0.042733                         (Almond Croissant)
8   0.042520                           (Vanilla Eclair)
38  0.042440                              (Almond Bear)
26  0.042387                         (Vanilla Meringue)
6   0.042373                         (Chocolate Eclair)
13  0.042360                             (Apricot Tart)
10  0.042040                              (Almond Tart)
25  0.041933                       (Chocolate Meringue)
59  0.041107  (Opera Cake, Cherry Tart, Apricot Danish)

In [9]:
ccake_support = bake_f[bake_f["itemsets"] == {'Chocolate Cake'}]["support"].values[0]
print(ccake_support)

0.08353333333333333

In [10]:
ccoffee_support = bake_f[bake_f["itemsets"] == {'Chocolate Coffee'}]["support"].values[0]
print(ccoffee_support)

0.08314666666666666

In [11]:
pair_support = bake_f[bake_f["itemsets"] == {'Chocolate Coffee','Chocolate Cake'}]["support"].values[0]
print(pair_support)

0.04404

In [12]:
all_n = intial_bakery_df["Transaction Number"].count()
all_n

75000

In [20]:
fp1 = np.ceil(all_n*ccoffee_support)
fp1

6236.0

In [21]:
f1p = np.ceil(all_n*ccake_support)
f1p

6265.0

In [22]:
f11 = np.ceil(all_n*pair_support)
f11

3303.0

In [23]:
f01 = fp1 - f11
f01

2933.0

In [24]:
f10 = f1p - f11
f10

2962.0

In [25]:
f0p = all_n - f1p
f0p

68735.0

In [26]:
fp0 = all_n - fp1
fp0

68764.0

In [27]:
f00 = fp0 - f10 
f00

65802.0

In [33]:
f0p - f01 == f00

True

In [34]:
f00 + f01 == f0p

True

In [35]:
f00 + f10 == fp0

True

In [36]:
f11 + f10 == f1p

True

In [37]:
f11 + f01 == fp1

True

In [82]:
print("\t","Coco","\t\t","!Coco","\t")
print()
print("Cake", "\t",f11,"\t",f10,"\t",f1p)
print()
print("!Cake","\t",f01,"\t",f00,"\t",f0p)
print()
print("\t", fp1, "\t", fp0, "\t", all_n)

	 Coco 		 !Coco

Cake 	 3303.0 	 2962.0 	 6265.0

!Cake 	 2933.0 	 65802.0 	 68735.0

	 6236.0 	 68764.0 	 75000

In [86]:
corr = (f11*f00 - f10*f01)/np.sqrt(fp1*f1p*fp0*f0p)
corr

0.4855664925278768